apiVersion: serving.knative.dev/v1 #version pour les objet managés par Serving
kind: Service #service Knative
metadata:
  name: quote-service
spec:
  template:
    spec:
      containers:
        - name: quote-service
          image: ghcr.io/alexandresb/quote-service
          ports:
            - containerPort: 9101
          resources:
            requests:
              cpu: '0.1'
              memory: '128Mi'
            limits:
              cpu: '2'
              memory: '512Mi'
